### ISSUE TITLE
difference between TOP vs application

### ISSUE THREAD

**Issue by bebeun** [schneems/derailed_benchmarks#102]
hi, 

running derailed in "local" production (`RAILS_ENV=production bundle exec derailed exec perf:mem`) gives me this : 

TOP: 173.7539 MiB
  application: 26.3008 MiB

while in dev I have (`bundle exec derailed bundle:mem development`) : 

TOP: 48.4063 MiB
  rails/all: 18.8047 MiB

My app do take about 180 mib on heroku. I am desperately trying to low this value. Any clue about where to look  ? what does TOP mean ?

Thk U !!

**Comment by bebeun** [comment]
ok, 
`RAILS_ENV=production bundle exec derailed exec perf:mem`
gives 
TOP: 179.6563 MiB
  application: 35.5156 MiB
while
`bundle exec derailed bundle:mem production`
gives 
TOP: 51.0273 MiB
  rails/all: 18.7852 MiB

I really don't understand the difference. 

Any help ?

**Comment by schneems** [comment]
TOP is the amount of memory that is consumed by the whole process.

`bundle:mem` does not actually boot your app, it only loads your dependencies into memory, so basically we're saying that 51mb of memory come from just loading your dependencies. `perf:mem` also boots your application. This is important because sometimes gems or code are lazy loaded i.e. if you have `require 'foo'` somewhere in the boot process itself. Rails will do this, it only loads the things it needs as it needs them. So 179mb is the likely actual RAM use of your app when it first boots but has not yet done taken any requests. 

I think `application` refers to the code in your app, as opposed to dependencies, but I kinda forget. If you have a full output and can post to a gist, I can maybe be of more help.
