### ISSUE TITLE
Memory leak in an empty rails app?

### ISSUE THREAD

**Issue by patrick99e99** [schneems/derailed_benchmarks#93]
I've got a production rails app which has been having issues as far as the server running out of memory consistently over time.  I came across your gem and thought I'd try it out, and sure enough just hitting an endpoint, I consistently saw the memory output in the file being written to tmp going up and up...

However, I wanted to prove that this was in fact demonstrating the problem, so I created a new rails app (4.1.4) with ruby 2.2.5, made a single controller with an action that does:

    def index
      head 200
    end

When I tried hitting that endpoint with `bundle exec derailed exec perf:mem_over_time`, the results I get are:

https://gist.github.com/patrick99e99/1fcb853bbc3fdc939053a6818462f78b

which does basically the same thing..  the number goes up and up and up.................. So......... I am a little confused?  Does a brand new rails app that does nothing have a memory leak?  Or am I misreading these numbers and this i actually not a problem?

**Comment by benoittgt** [comment]
Hello @patrick99e99 

Memory increasing doesn't mean your app have memory leaks. 
You should read https://github.com/puma/puma/issues/1047 (lot's of great comments about memory) and check talks of [Richard Schneeman](https://www.youtube.com/watch?v=xii1oyad_kc) or [Nate Berkopec](https://www.youtube.com/watch?v=kZcqyuPeDao) about memory.

**Comment by nateberkopec** [comment]
The key thing is that GC does not run all the time, it only is triggered after certain thresholds are met.

Try this: 

```
def index
  GC.start
  head 200
end
```

voila, memory growth will (mostly) disappear. the remaining growth you see is fragmentation from malloc. run it for ~10k requests and you'll see it level off.

**Comment by srghma** [comment]
@nateberkopec I've run `TEST_COUNT=200_000 PATH_TO_HIT=/ bundle exec derailed exec perf:mem_over_time` on new rails project and got this image

![2018-07-20-12 52 06-screenshot](https://user-images.githubusercontent.com/7573215/42996405-1b6bfdc0-8c1c-11e8-9815-d72d7ba27d28.png)

**Comment by srghma** [comment]
TEST_COUNT=200_000 = 339 entries

I'm not sure now that TEST_COUNT means `number or requests`

**Comment by schneems** [comment]
For future reference on memory issues if anyone else stumbles across this issue:

- [Why does my App's Memory Use Grow Over Time?](https://www.schneems.com/2019/11/07/why-does-my-apps-memory-usage-grow-asymptotically-over-time/ )  - Start here, a good high level overview of what causes a system's memory to grow that will help you develop an understanding of how Ruby allocates and uses memory at the application level.
- [Complete Guide to Rails Performance (Book)](https://www.railsspeed.com) - This book is by Nate Berkopec and is excellent. I recommend it to someone at least once a week.
- [How Ruby uses memory](https://www.sitepoint.com/ruby-uses-memory/) - This is a lower level look at precisely what "retained" and "allocated" memory means. It uses small scripts to demonstrate Ruby memory behavior. It also explains why the "total max" memory of our system rarely goes down.
- [How Ruby uses memory (Video)](https://www.schneems.com/2015/05/11/how-ruby-uses-memory.html) - If you're new to the concepts of object allocation this might be an excellent place to start (you can skip the first story in the video, the rest are about memory). Memory stuff starts at 13 minutes 
- [Jumping off the Ruby Memory Cliff](https://www.schneems.com/2017/04/12/jumping-off-the-memory-cliff/) - Sometimes you might see a 'cliff' in your memory metrics or a saw-tooth pattern. This article explores why that behavior exists and what it means.
- [Ruby Memory Use (Heroku Devcenter article I maintain)](https://devcenter.heroku.com/articles/ruby-memory-use) - This article focuses on alleviating the symptoms of high memory use.
- [Debugging a memory leak on Heroku](https://blog.codeship.com/debugging-a-memory-leak-on-heroku/) - TLDR; It's probably not a leak. Still worth reading to see how you can come to the same conclusions yourself. Content is valid for other environments than Heroku. Lots of examples of using the tool `derailed_benchmarks` (that I wrote).
- [The Life-Changing Magic of Tidying Active Record Allocations (Video)](https://www.youtube.com/watch?v=CS11WIalmPM&feature=emb_title) - This talk shows how I used tools to track down and eliminate memory allocations in real life. All of the examples are from patches I submitted to Rails, but the process works the same for finding allocations caused by your application logic.
