### ISSUE TITLE
Memory allocated by gem

### ISSUE THREAD

**Issue by vishnurkrishnan** [schneems/derailed_benchmarks#96]
This is not an issue, one clarification I have been using this derailed gem to identify the memory issues and when i try this mem. Ruby 2.2.2, Rails 3.2.22

bundle exec derailed bundle:mem

 TOP: 55.3398 MiB
  delayed_job_active_record: 15.8789 MiB
    delayed_job: 14.5352 MiB (Also required by: delayed/railtie)
    delayed/yaml_ext: 10.4688 MiB

but when i try that objects

allocated memory by gem

 35887974  activesupport-3.2.22
 7594834  mime-types-1.25.1
 7076454  newrelic_rpm-3.9.8.273
 6541589  mail-2.5.4

I think there is more memory taking for this mime-types and newrelic, right? and if should i update the gem mail? i am following this link https://blog.codeship.com/debugging-a-memory-leak-on-heroku/

**Comment by schneems** [comment]
Here's some memory resources:

- [Why does my App's Memory Use Grow Over Time?](https://www.schneems.com/2019/11/07/why-does-my-apps-memory-usage-grow-asymptotically-over-time/ )  - Start here, a good high level overview of what causes a system's memory to grow that will help you develop an understanding of how Ruby allocates and uses memory at the application level.
- [Complete Guide to Rails Performance (Book)](https://www.railsspeed.com) - This book is by Nate Berkopec and is excellent. I recommend it to someone at least once a week.
- [How Ruby uses memory](https://www.sitepoint.com/ruby-uses-memory/) - This is a lower level look at precisely what "retained" and "allocated" memory means. It uses small scripts to demonstrate Ruby memory behavior. It also explains why the "total max" memory of our system rarely goes down.
- [How Ruby uses memory (Video)](https://www.schneems.com/2015/05/11/how-ruby-uses-memory.html) - If you're new to the concepts of object allocation this might be an excellent place to start (you can skip the first story in the video, the rest are about memory). Memory stuff starts at 13 minutes 
- [Jumping off the Ruby Memory Cliff](https://www.schneems.com/2017/04/12/jumping-off-the-memory-cliff/) - Sometimes you might see a 'cliff' in your memory metrics or a saw-tooth pattern. This article explores why that behavior exists and what it means.
- [Ruby Memory Use (Heroku Devcenter article I maintain)](https://devcenter.heroku.com/articles/ruby-memory-use) - This article focuses on alleviating the symptoms of high memory use.
- [Debugging a memory leak on Heroku](https://blog.codeship.com/debugging-a-memory-leak-on-heroku/) - TLDR; It's probably not a leak. Still worth reading to see how you can come to the same conclusions yourself. Content is valid for other environments than Heroku. Lots of examples of using the tool `derailed_benchmarks` (that I wrote).
- [The Life-Changing Magic of Tidying Active Record Allocations (Video)](https://www.youtube.com/watch?v=CS11WIalmPM&feature=emb_title) - This talk shows how I used tools to track down and eliminate memory allocations in real life. All of the examples are from patches I submitted to Rails, but the process works the same for finding allocations caused by your application logic.
